# Intro to Pandas
___

**pandas** provides data structures and data manipulation tools designed for fast & easy data cleaning and analysis.

pandas adopts array-based computing from NumPy, but is designed for **tabular** or **heterogenous** data.

pandas has two primary data structures:

- **Series** - one-dimensional array-like object with a sequence of values having the same datatype
- **DataFrame** - rectangular table of data with ordered collection of columns, each of which can be a different value type

In [2]:
#As allways we import pandas and numpy
import pandas as pd
import numpy as np

### Series

Has a sequence of values (all the same datatype) and an associated array of data labels called its **index**. If not specified otherwise, the index values are sequential integers.

pandas can automatically determine datatype of values when a Series is created, but datatype can also be specified.

A Series is like a fixed-length, ordered dict with a mapping of index values to data values.

The array representation and index object of a Series can be accessed via its **values** and **index** attributes.

Problem 1: Create a series 4 numerical values. Print the series, the values and the index of the series.

In [19]:
pandas_series = pd.Series([1, 2, 3, 4])
print(pandas_series)
print(pandas_series.array)
print(pandas_series.index)

0    1
1    2
2    3
3    4
dtype: int64
<NumpyExtensionArray>
[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)

Problem 2: Create a new series with the same values but with string values for the index. Select and print out one of the values in the series with the index.

In [17]:
series2 = pd.Series([1, 2, 3, 4], index = ["a", "b", "c", "d"])
print(series2["a"])

1

Problem 3: You can also create a series from a python dict. Create a dict called `states_dict` with the state name as the key and the number as the value.
'Ohio' 35000
'Texas' 71000
'Oregon' 16000 
'Utah' 5000
Use the dict `states_dict` to create a series called `states_series`.

In [22]:
states_dict = {"Ohio": 35000, "Texas": 71000,
               "Oregon": 16000, "Utah":5000}
states_series = pd.Series(states_dict)
print(states_series)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Problem 4: Updated the index of `state_series` to be the abbreviation of the state names. Do this in place.

In [23]:
states_series.index = ["OH", "TX", "OR", "UT"]
print(states_series)

OH    35000
TX    71000
OR    16000
UT     5000
dtype: int64

### DataFrame

A pandas DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type.

Sort of a dict of Series all sharing the same index.

- DataFrames have both row and column indices
- DataFrames are physically 2D, but can represent higher-dimensional data using hierarchical indexing
- DataFrame rows are sometimes referred to as axis=0
- DataFrame columns are sometimes referred to as axis=1


You can create DataFrames from dicts as well.

In [24]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
      }

df = pd.DataFrame(data)
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Problem 5: Update the index of the DataFrame df to be the words for each number. i.e. 1 -> one

In [27]:
df.index = ["zero", "one", "two", "three", "four", "five"]
print(df)

        state  year  pop
zero     Ohio  2000  1.5
one      Ohio  2001  1.7
two      Ohio  2002  3.6
three  Nevada  2001  2.4
four   Nevada  2002  2.9
five   Nevada  2003  3.2

Problem 6: Figure out two ways to access a column from df. Output the results.

In [34]:
print(df["year"])
print("\n")
print(df.iloc[:, 0])

zero     2000
one      2001
two      2002
three    2001
four     2002
five     2003
Name: year, dtype: int64


zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object

Problem 7: Figure out two ways to access a row from df. Output the results.

In [49]:
print(df.loc["two"])
print(df.iloc[2])

state    Ohio
year     2002
pop       3.6
Name: two, dtype: object
state    Ohio
year     2002
pop       3.6
Name: two, dtype: object

Problem 8: Add a new column to your dataframe called 'rating' with the values `[5,4,3,2,1,0]`

In [51]:
df["rating"] = np.arange(5, -1, -1)
print(df)

        state  year  pop  rating
zero     Ohio  2000  1.5       5
one      Ohio  2001  1.7       4
two      Ohio  2002  3.6       3
three  Nevada  2001  2.4       2
four   Nevada  2002  2.9       1
five   Nevada  2003  3.2       0

Problem 9: Create another column called `nonsense` that is the rating multiplied by the pop.

In [53]:
df["nonsense"] = df["rating"] * df["pop"]
print(df)

        state  year  pop  rating  nonsense
zero     Ohio  2000  1.5       5       7.5
one      Ohio  2001  1.7       4       6.8
two      Ohio  2002  3.6       3      10.8
three  Nevada  2001  2.4       2       4.8
four   Nevada  2002  2.9       1       2.9
five   Nevada  2003  3.2       0       0.0

Problem 10: Create three series using using numpy.

* series_numerical: The values 0-4 with index a-e
* series_zeros: All zeros with index a-e
* series_random: 5 random numbers qith index a-e

DataFrame called `numeric_df` from these three series. Each series will be a row and the columns will be a-e.

In [6]:
numbers = np.array([0, 1, 2, 3, 4])
zeros = np.zeros(5)
random_nums = np.random.rand(5)




series_numerical = pd.Series(numbers, index=["a","b","c","d","e"])
series_zeros = pd.Series(zeros, index=["a","b","c","d","e"])
series_random = pd.Series(random_nums, index =["a","b","c","d","e"])
numeric_df = pd.DataFrame({"series_numerical": series_numerical,
                            "series_zeros": series_zeros,
                              "series_random": series_random})
print(numeric_df)

   series_numerical  series_zeros  series_random
a                 0           0.0       0.516706
b                 1           0.0       0.742704
c                 2           0.0       0.487931
d                 3           0.0       0.460146
e                 4           0.0       0.542536

Problem 11: Transpose the DataFrame `numeric_df` so that the series become columns instead of rows. Save this to a variable called `transposed_numeric_df`. Rename the columns to `numerical`, `zeros`, and `random`.

In [26]:
transposed_numeric_df = numeric_df.T.loc[:,["a", "b", "c" ]].rename(
    columns={"a": "numerical", "b": "zeros", "c": "random"}
)
transposed_numeric_df

                  numerical     zeros    random
series_numerical   0.000000  1.000000  2.000000
series_zeros       0.000000  0.000000  0.000000
series_random      0.516706  0.742704  0.487931

Problem 12: Output `transposed_numeric_df` ordered by `random` descending.

In [27]:
transposed_numeric_df.sort_values(by="random", ascending = False)
print(transposed_numeric_df)

                  numerical     zeros    random
series_numerical   0.000000  1.000000  2.000000
series_zeros       0.000000  0.000000  0.000000
series_random      0.516706  0.742704  0.487931

Problem 13: Select all rows from `transposed_numeric_df` where the column `numerical` is greater than 2.

In [28]:
greater_than_two = transposed_numeric_df[transposed_numeric_df["numerical"] > 2]
greater_than_two

Empty DataFrame
Columns: [numerical, zeros, random]
Index: []

Problem 14: Add a column called `random_5` that is the column random multiplied by 5. Select all rows from `transposed_numeric_df` where `numerical` is greater than `random_5`.

In [35]:
transposed_numeric_df["random_5"] = transposed_numeric_df["random"] * 5 
print(transposed_numeric_df)
greater_than_random_5 = transposed_numeric_df[transposed_numeric_df["numerical"] > transposed_numeric_df["random_5"]]

greater_than_random_5

                  numerical     zeros    random   random_5
series_numerical   0.000000  1.000000  2.000000  10.000000
series_zeros       0.000000  0.000000  0.000000   0.000000
series_random      0.516706  0.742704  0.487931   2.439657

Empty DataFrame
Columns: [numerical, zeros, random, random_5]
Index: []

Problem 15: Add a column to transposed_numberic_df called `even` that is True when `numerical` is even and `False` when `numerical` is odd.

In [36]:
transposed_numeric_df["even"] = transposed_numeric_df["numerical"] % 2 == 0


transposed_numeric_df

                  numerical     zeros    random   random_5   even
series_numerical   0.000000  1.000000  2.000000  10.000000   True
series_zeros       0.000000  0.000000  0.000000   0.000000   True
series_random      0.516706  0.742704  0.487931   2.439657  False

Problem 16: Add a column called `even_odd` that has the value `odd` when `numerical` is odd and `even` when `numerical` is even.

In [40]:
transposed_numeric_df["even_odd"] = np.where(transposed_numeric_df["numerical"] % 2 != 0, "odd", "even")
transposed_numeric_df

                  numerical     zeros    random   random_5   even even_odd
series_numerical   0.000000  1.000000  2.000000  10.000000   True     even
series_zeros       0.000000  0.000000  0.000000   0.000000   True     even
series_random      0.516706  0.742704  0.487931   2.439657  False      odd

Problem 17: Print out the sum of all columns.

In [42]:
sum_columns = transposed_numeric_df.sum()
print(sum_columns)

numerical       0.516706
zeros           1.742704
random          2.487931
random_5       12.439657
even                   2
even_odd     evenevenodd
dtype: object

Problem 18: Print out index of the row with the max value for each column. i.e. for `numerical` it will be the last row `e` because it has a value of 5.

In [ ]:
transposed_numeric_df["numerical"].idxmax()

'series_random'