# Week 8 Overview

This week will be a mix of data joining/merging problems and linear algebra. 
The first 5 problems are data cleaning and the final 4 problems are linear algebra.

There are multiple ways to combine data. These methods are common cross multiple languages like pandas, SQL, and R. At times the naming is different but the general concepts apply. 

### **Joining or Merging**
This is a process of combining two datasets by adding the columns of one dataset to the other by some logical relationship between the columns. 

In SQL we call this joining but pandas has two functions:

**merge** - The default behavor for merge is to combine on columns matching.

**join** - The default behavor for join is to combine on the column index matching. 

Often times I will colloquially use the word "join" for either merging or joining in pandas. 

Left Dataset
| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |

Right Dataset
| key    | different_value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

Data Joined on key

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | cat |
| A2 | $80     | dog |
| A3    | $420    | apple |

Typically we refer to the starting dataset as the left dataset and the one being added as the right. 

The logic is typically that there is the same value in a specific column in both datasets. SQL allows for slightly more advanced logic which we will learn next quarter. Today we will focus on just columns matching. 

There are different types of joins that you will explore in this notebook (inner, outer, left, right, cross). The typical visual that is used to illustration these concepts in Ven Diagrams. If you are getting stuck trying to pick the right join type search for "types of joins" and look at the pictures that come up.


## **Concat or Union**

This is a process of combining two dataset by adding the rows of one dataset to the end of another. There is no logic required for this. This is called conact in pandas and union in SQL. 

In most version of SQL you are required to have the same columns in both datasets. In pandas you don't have to. If I concatenate the two dataset above in pandas I would get:

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | null |
| A2 | $80     | null |
| A3    | $420    | null |
| A1  | null    | cat |
| A2 | null     | dog |
| A3    | null    | apple |

However if my right dataset looked like this:

| key    | value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

then I could union them in SQL or concat in pandas to get:

| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

In [1]:
import pandas as pd
import numpy as np

In [3]:
df_1 = pd.DataFrame({"ints": range(100)})
df_2 = pd.DataFrame({"ints": range(-10, 10)}, index=range(-10, 10))


df_1['threes'] = np.floor(df_1['ints']/3) * 3

df_2['evens'] = df_2['ints']*2
df_2['threes'] = np.floor(df_2['ints']/3) * 3

### Problem 1:

Your first task will be to create a dataset by `merging` `df_1` and `df_2` on the `ints` column where the match on both sides. The results will be a dataframe with 10 rows and 5 columns.

You will then create the same dataframe by using the `join` function and joining the two datasets where the indexes are equal. There will be a little more work of handle column duplication so look up the error and figure out arguments to set. How many columns do you get in this case?

In [5]:
merged_df = pd.merge(df_1, df_2, on="ints")
print(merged_df)

   ints  threes_x  evens  threes_y
0     0       0.0      0       0.0
1     1       0.0      2       0.0
2     2       0.0      4       0.0
3     3       3.0      6       3.0
4     4       3.0      8       3.0
5     5       3.0     10       3.0
6     6       6.0     12       6.0
7     7       6.0     14       6.0
8     8       6.0     16       6.0
9     9       9.0     18       9.0

In [14]:
merged_df2 = df_1.join(df_2, how = 'inner', lsuffix='left', rsuffix = 'right')
merged_df2 = merged_df2.drop(columns=['intsright'])
print(merged_df2)

   intsleft  threesleft  evens  threesright
0         0         0.0      0          0.0
1         1         0.0      2          0.0
2         2         0.0      4          0.0
3         3         3.0      6          3.0
4         4         3.0      8          3.0
5         5         3.0     10          3.0
6         6         6.0     12          6.0
7         7         6.0     14          6.0
8         8         6.0     16          6.0
9         9         9.0     18          9.0

## Problem 2:

Next you will perform the same merge as above three times with the following modifications:

* You want to keep all rows in `df_1` even if there is no match found in `df_2`
* You want to keep all rows in `df_2` even if there is no match found in `df_1`
* You want to keep all rows in `df_1` and `df_2` even if there is no match found in the other dataframe


How many rows do you end up with in each case? 

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [ ]:
#we would use this case if there was ever a scenario in which we have customer 
#id in the left table and want to look at all entries from the right table 

result_1 = df_1.join(df_2, how = "left", lsuffix = "_df1", rsuffix = "_df2")
result_1.head(15)

    ints_df1  threes_df1  ints_df2  evens  threes_df2
0          0         0.0       0.0    0.0         0.0
1          1         0.0       1.0    2.0         0.0
2          2         0.0       2.0    4.0         0.0
3          3         3.0       3.0    6.0         3.0
4          4         3.0       4.0    8.0         3.0
5          5         3.0       5.0   10.0         3.0
6          6         6.0       6.0   12.0         6.0
7          7         6.0       7.0   14.0         6.0
8          8         6.0       8.0   16.0         6.0
9          9         9.0       9.0   18.0         9.0
10        10         9.0       NaN    NaN         NaN
11        11         9.0       NaN    NaN         NaN
12        12        12.0       NaN    NaN         NaN
13        13        12.0       NaN    NaN         NaN
14        14        12.0       NaN    NaN         NaN

In [ ]:
#

result_2 = df_2.join(df_1, how = "left", lsuffix = "_df2", rsuffix = "_df1")
result_2.head(15)

     ints_df2  evens  threes_df2  ints_df1  threes_df1
-10       -10    -20       -12.0       NaN         NaN
-9         -9    -18        -9.0       NaN         NaN
-8         -8    -16        -9.0       NaN         NaN
-7         -7    -14        -9.0       NaN         NaN
-6         -6    -12        -6.0       NaN         NaN
-5         -5    -10        -6.0       NaN         NaN
-4         -4     -8        -6.0       NaN         NaN
-3         -3     -6        -3.0       NaN         NaN
-2         -2     -4        -3.0       NaN         NaN
-1         -1     -2        -3.0       NaN         NaN
0           0      0         0.0       0.0         0.0
1           1      2         0.0       1.0         0.0
2           2      4         0.0       2.0         0.0
3           3      6         3.0       3.0         3.0
4           4      8         3.0       4.0         3.0

In [ ]:
#use outer join when we don't want to omit any rows even if info is missing 

result_3 = df_1.join(df_2, how = "outer", lsuffix = "_df1", rsuffix = "_df2")
result_3.head(15)

     ints_df1  threes_df1  ints_df2  evens  threes_df2
-10       NaN         NaN     -10.0  -20.0       -12.0
-9        NaN         NaN      -9.0  -18.0        -9.0
-8        NaN         NaN      -8.0  -16.0        -9.0
-7        NaN         NaN      -7.0  -14.0        -9.0
-6        NaN         NaN      -6.0  -12.0        -6.0
-5        NaN         NaN      -5.0  -10.0        -6.0
-4        NaN         NaN      -4.0   -8.0        -6.0
-3        NaN         NaN      -3.0   -6.0        -3.0
-2        NaN         NaN      -2.0   -4.0        -3.0
-1        NaN         NaN      -1.0   -2.0        -3.0
 0        0.0         0.0       0.0    0.0         0.0
 1        1.0         0.0       1.0    2.0         0.0
 2        2.0         0.0       2.0    4.0         0.0
 3        3.0         3.0       3.0    6.0         3.0
 4        4.0         3.0       4.0    8.0         3.0

### Problem 3

Now we are going to merge on columns that are not the same. Merge on the following:

* Merge `df_1` and `df_2` where `df_1.ints = df_2.evens`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, keep all rows from `df_1` even if there is no match found in `df_2`
* Merge `df_1` and `df_2` where `df_1.threes = df_2.threes`, only keep rows where there is a value for either dataframe


How many rows do you end up with in each case? Are there any duplications? (try: value_count)

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [30]:
merged_df3 = pd.merge(df_1, df_2, left_on = 'ints', right_on = 'evens')
merged_df3.head(15)

   ints_x  threes_x  ints_y  evens  threes_y
0       0       0.0       0      0       0.0
1       2       0.0       1      2       0.0
2       4       3.0       2      4       0.0
3       6       6.0       3      6       3.0
4       8       6.0       4      8       3.0
5      10       9.0       5     10       3.0
6      12      12.0       6     12       6.0
7      14      12.0       7     14       6.0
8      16      15.0       8     16       6.0
9      18      18.0       9     18       9.0

In [29]:
merged_df4 = pd.merge(df_1, df_2, left_on = 'ints', right_on = 'threes')
merged_df4.head(15)

   ints_x  threes_x  ints_y  evens  threes_y
0       0       0.0       0      0       0.0
1       0       0.0       1      2       0.0
2       0       0.0       2      4       0.0
3       3       3.0       3      6       3.0
4       3       3.0       4      8       3.0
5       3       3.0       5     10       3.0
6       6       6.0       6     12       6.0
7       6       6.0       7     14       6.0
8       6       6.0       8     16       6.0
9       9       9.0       9     18       9.0

In [31]:
merged_df5 = pd.merge(df_1, df_2, how = 'left', left_on = 'ints', right_on = 'threes')
merged_df5.head(15)

    ints_x  threes_x  ints_y  evens  threes_y
0        0       0.0     0.0    0.0       0.0
1        0       0.0     1.0    2.0       0.0
2        0       0.0     2.0    4.0       0.0
3        1       0.0     NaN    NaN       NaN
4        2       0.0     NaN    NaN       NaN
5        3       3.0     3.0    6.0       3.0
6        3       3.0     4.0    8.0       3.0
7        3       3.0     5.0   10.0       3.0
8        4       3.0     NaN    NaN       NaN
9        5       3.0     NaN    NaN       NaN
10       6       6.0     6.0   12.0       6.0
11       6       6.0     7.0   14.0       6.0
12       6       6.0     8.0   16.0       6.0
13       7       6.0     NaN    NaN       NaN
14       8       6.0     NaN    NaN       NaN

In [33]:
merged_df6 = pd.merge(df_1, df_2, how = 'outer', left_on = 'threes', right_on = 'threes')
merged_df6.head(15)

    ints_x  threes  ints_y  evens
0      NaN   -12.0   -10.0  -20.0
1      NaN    -9.0    -9.0  -18.0
2      NaN    -9.0    -8.0  -16.0
3      NaN    -9.0    -7.0  -14.0
4      NaN    -6.0    -6.0  -12.0
5      NaN    -6.0    -5.0  -10.0
6      NaN    -6.0    -4.0   -8.0
7      NaN    -3.0    -3.0   -6.0
8      NaN    -3.0    -2.0   -4.0
9      NaN    -3.0    -1.0   -2.0
10     0.0     0.0     0.0    0.0
11     0.0     0.0     1.0    2.0
12     0.0     0.0     2.0    4.0
13     1.0     0.0     0.0    0.0
14     1.0     0.0     1.0    2.0

### Problem 4

Add a new the column to `df_2` called `threes_string` that is the `threes` column converted to a string. Attempt to merge `df_1` and `df_2` where `df_1.threes = df_2.threes_string` with an inner join. What happens? Why?

In [ ]:
df_2['threes_string'] = df_2['threes'].astype(str) 
merged_df7 = pd.merge(df_1, df_2, how = 'inner', left_on = 'threes', right_on = 'threes_string')
merged_df7.head(15) 

#theres an error because its a type mismatch so if we inner join
# "3" with 3, since "3" will never be equivalent to int 3 it causes a error

KeyError: 'threes'

### Problem 5

Now you will play around with `pd.concat` by doing the following:

* Concatenate `df_1` and `df_2` keeping all rows, columns and indexes
* Concatenate `df_1` and `df_2` keeping all rows and columns but ignore the indexes from the orginal dataframes and instead have the index on this dataframe be zero to the number of rows.
* Concatenate `df_1` and `df_2` keeping all rows and indexes the same but only keeping columns that exist in both dataframes

In [41]:
concatenated_df = pd.concat([df_1, df_2])

concatenated_df2 = pd.concat([df_1, df_2], ignore_index = True)


concatenated_df3 = pd.concat([df_1, df_2], join = "inner" )

print("concatenate with all rows columns and indexes: " )
display(concatenated_df.head(10))

print("concatenate with all rows and column but ignore index: ")
display(concatenated_df2.head(10))

print("concatenate but only keep columns in both dataframes: " )
display(concatenated_df3.head(10))

concatenate with all rows columns and indexes:

   ints threes
0   0.0    0.0
1   1.0    0.0
2   2.0    0.0
3   3.0    3.0
4   4.0    3.0
5   5.0    3.0
6   6.0    6.0
7   7.0    6.0
8   8.0    6.0
9   9.0    9.0

concatenate with all rows and column but ignore index:

   ints  threes    0
0   0.0     0.0  NaN
1   1.0     0.0  NaN
2   2.0     0.0  NaN
3   3.0     3.0  NaN
4   4.0     3.0  NaN
5   5.0     3.0  NaN
6   6.0     6.0  NaN
7   7.0     6.0  NaN
8   8.0     6.0  NaN
9   9.0     9.0  NaN

concatenate but only keep columns in both dataframes:

  threes
0    0.0
1    0.0
2    0.0
3    3.0
4    3.0
5    3.0
6    6.0
7    6.0
8    6.0
9    9.0

## Linear Algebra: Rank and Column Space

### Problem 6
You will now learn how to create random matrices with arbitrary rank (subject to the constraints about matrix sizes, etc.). To create an $m \times n$ matrix with rank $r$, multiply a random $m \times r$ matrix with a random $r \times n$ matrix. Implement this in Python and confirm that the rank is indeed $r$. 

What happens if you set $r > min{M,N}$, and why does that happen?

In [43]:
m = 5
n = 4
r = 3 

matrix_A = np.random.randn(m, r) #5x3 
matrix_B = np.random.randn(r, n) #3x4 

matrix_C = matrix_A @ matrix_B 

rank_C = np.linalg.matrix_rank(matrix_C)

print(f"matrix of {m}x{n}, expected rank = {r}, result = {rank_C}")

matrix of 5x4, expected rank = 3, result = 3

### Problem 7
Interestingly, the matrices $A$, $A^T$, $A^T A$, and $AA^T$ all have the same rank. Write code to demonstrate this, using random matrices of various sizes, shapes (square, tall, wide), and ranks. Create a total of 6 random, two of each size that have different sizes and ranks.

In [45]:
square_matrix1 = np.random.randint(low = 0, high = 10, size=(2,2))
square_matrix2 = np.random.randint(low = 0, high = 10, size=(4,4))

tall_matrix1 = np.random.randint(low = 0, high = 10, size =(4, 2))
tall_matrix2 = np.random.randint(low = 0, high = 10, size = (6, 3))

wide_matrix1 = np.random.randint(low = 0, high = 10, size=(2, 4))
wide_matrix2 = np.random.randint(low = 0, high = 10, size=(3, 6)) 


sq1 = np.linalg.matrix_rank(square_matrix1)
sq2 = np.linalg.matrix_rank(square_matrix1.T)
sq3 = np.linalg.matrix_rank(square_matrix1.T @ square_matrix1)
sq4 = np.linalg.matrix_rank(square_matrix1 @ square_matrix1.T) 

print(f"ranks: {sq1}, {sq2}, {sq3}, {sq4}")

ranks: 2, 2, 2, 2

### Problem 8

Demonstrate the addition rule of matrix rank $(r(A + B) ≤ r(A) + r(B))$ by creating three pairs of rank-1 matrices that have a sum with 
1. rank-0
2. rank-1
3. rank-2

Then repeat this exercise using matrix multiplication instead of addition.

### Problem 9

The goal of this exercise is to answer the question is $v \in C(A)$?

Create a rank-3 matrix $A \in \mathbb{R}^{4 \times 3}$ and vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. 

Follow the algorithm described in the [In the Column Space?](https://learning.oreilly.com/library/view/practical-linear-algebra/9781098120603/ch06.html#id335) section of Practical Linear Algebra to determine whether the vector is in the column space of the matrix. 

Rerun the code multiple times to see whether you find a consistent pattern. 

Next, use a $A \in \mathbb{R}^{4 \times 4}$ rank-4 matrix and a vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. What happens in this case? Why?